### ISSUE TITLE
Add function deprecation notes in help pages

### ISSUE THREAD

**Issue by bauer-alex** [bluefoxr/COINr#10]
Issue based on the JOSS revision process (see [the corresponding issue](https://github.com/openjournals/joss-reviews/issues/4567)).

The package contains a lot of exported functions which are deprecated. Printing the `COINr:::defunct_message()` when such functions are called seems like a good idea. Only thing I also would to see is a short deprecation note (can be identical to the defunct message) in the help page (e.g. `?COINr::getPCA`) for full clarity.

**Comment by bluefoxr** [comment]
OK good point, I will do this.

**Comment by bluefoxr** [comment]
I have now added deprecation notes to all the relevant functions - see commit here: https://github.com/bluefoxr/COINr/commit/f98fc6df5a9fd08ce67caf11cc41f275fd8b8701

I'll close this issue now, because I presume it is fixed - if not, please open a separate issue. Thanks.
