### ISSUE TITLE
Distance to target

### ISSUE THREAD

**Issue by bluefoxr** [bluefoxr/COINr#12]
Enable distance to target to work using coin targets. Also possibly add two-ended targets.

**Comment by chloebellamyFR** [comment]
Hi Will,
I'm trying to run distance to target, on a coin, but getting an error "Error in stopifnot(is.numeric(x), is.numeric(targ), length(targ) == 1,  :   argument "targ" is missing, with no default"
I have added the Target column to iMeta, but it doesn't seem to have copied over to my coin when I built it. Is this the issue that this bug refers to please? Thanks!

**Comment by bluefoxr** [comment]
Hi, which version of COINr are you using? There have been some recent fixes to address this issue, so if you didn't already, please install the latest dev version:

```
# Install development version from GitHub
devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("bluefoxr/COINr")
```

Then try following the examples here: https://bluefoxr.github.io/COINr/articles/normalise.html#use-of-targets

If the problem persists please send me the command you are running and the data needed to run the command, e.g. your coin and the exact command, so I can reproduce the error. Thanks!

**Comment by bluefoxr** [comment]
Hi just clearing up old issues - please note in the latest version of COINr there is more flexibility for targets and other normalisation parameters stored in iMeta: see https://bluefoxr.github.io/COINr/articles/normalise.html#goalposts-targets-and-imeta-specification

Closing this issue now.
