### ISSUE TITLE
paper.md illustrate the problem the software is designed to solve

### ISSUE THREAD

**Issue by paulrougieux** [bluefoxr/COINr#15]
Related to the JOSS review https://github.com/openjournals/joss-reviews/issues/4567

For example in issue #6  Alex Bauer referenced another package called APCtools. The associated [JOSS paper](https://joss.theoj.org/papers/10.21105/joss.04056) illustrates the main features of the package with several figures (density matrix faceted plots and heat maps). Those figures are of great help to provide an overview of what the package can do. 

There is plenty of material in the COINr vignettes to provide an illustration of the software's main features, a selection of code examples and figures could be made available in the paper. Some examples from the [normalization](https://bluefoxr.github.io/COINr/articles/normalise.html) and obviously the [visualization](https://bluefoxr.github.io/COINr/articles/visualisation.html) vignette could be reused.

**Comment by bluefoxr** [comment]
hi @paulrougieux please see the amendments in commit https://github.com/bluefoxr/COINr/commit/b9a7721f11433565689b43f4c2a61aca4741cc9e

I have tried to strike a balance between adding a little more detail for the purposes of the paper, and respecting the requirement of brevity of the journal. The package is well documented at its website, so I have linked out as much as possible. Please see what you think and let me know if you see the need for adding more or changing something. Thanks.

**Comment by bluefoxr** [comment]
Compiled paper is here btw: https://github.com/bluefoxr/COINr/actions/runs/3055282246

**Comment by paulrougieux** [comment]
There is an issue with the current version of figure 1 
![Screenshot from 2022-09-15 10-48-38](https://user-images.githubusercontent.com/5647397/190359517-9c57d5ed-02cf-4720-8451-55c92163127d.png)

**Comment by paulrougieux** [comment]
The 2 figures have the same caption in the pdf version of the paper available [here](https://github.com/bluefoxr/COINr/actions/runs/3055306832).

**Comment by bluefoxr** [comment]
Sorry, I copied the code from another paper and forgot to change the captions. I have now fixed this, see https://github.com/bluefoxr/COINr/commit/29f0b934ce8f0024d9ee1abe0c2c8ec21582ea9a

**Comment by bluefoxr** [comment]
@paulrougieux do you think the paper modifications are sufficient to close the issue for now? Thanks

**Comment by paulrougieux** [comment]
The short introduction on how to build a coin is a good addition. I see you corrected figure titles, but figure 1 still has an issue with country 3 letters codes being very close to each other, maybe you can change this by changing the figure to a larger figure size in R, this is usually enough to force smaller fonts.

**Comment by paulrougieux** [comment]
I looked at the version in this run https://github.com/bluefoxr/COINr/actions/runs/3126882703 All the rest of paper.pdf is good for me.

**Comment by bluefoxr** [comment]
I have made the font a bit smaller for fig.1 - see https://github.com/bluefoxr/COINr/commit/c94c9d8f9cc65553cab523dcd957d7a184fd1c01 - I don't want to make it too much smaller because it might be hard to read.
