### ISSUE TITLE
Missing quote creates formating issue in help viewer

### ISSUE THREAD

**Issue by paulrougieux** [bluefoxr/COINr#18]
https://github.com/bluefoxr/COINr/blob/49faac222d7c86db84b6ae7356a61a0d98b27ed2/R/plot_corr.R#L14

   

A missing quote creates a formatting issue in my help viewer.

**Comment by bluefoxr** [comment]
Thanks, see https://github.com/bluefoxr/COINr/commit/27cfa023fc587a8402b65831fc261bb2eddfed73
I will close this issue now as I think it is definitely resolved
