### ISSUE TITLE
COINr::iplotMap to work with any given geojson

### ISSUE THREAD

**Issue by Edouard-Legoupil** [bluefoxr/COINr#2]
Hi, would be great to have the possibility to create maps at subbational scale.. 

Maybe we could add some parameters to the function @ https://github.com/bluefoxr/COINr/blob/8510fdefcd0c87ec4659e49b0ae7a9255c3504f9/R/coin_resultsdash.R#L278:L310 
to add the option to define a 

```
geojson
locations
featureidkey 
```

as displayed in this example:  https://plotly.com/r/choropleth-maps/

**Comment by bluefoxr** [comment]
Yeah thanks for the suggestion but this one I am not sure I will pursue. I want to keep COINr focused on the technical parts of composite indicator construction and analysis. The mapping aspect is of course important, but one can simply use the COINr results, load up plotly or whichever mapping package you prefer, and do it outside of COINr. I don't see the need to try to wrap everything inside COINr if it can be easily done outside the package.
