### ISSUE TITLE
Missing link to reference 

### ISSUE THREAD

**Issue by paulrougieux** [bluefoxr/COINr#20]
In https://bluefoxr.github.io/COINr/articles/sensitivity.html there is a missing link to the reference `10.1111/j.1467-985X.2005.00350.x`.

**Comment by bluefoxr** [comment]
Thanks, I fixed this now - see commit here: https://github.com/bluefoxr/COINr/commit/143a5b8eebcc033048ad23bede4abcf8d8bdac85

I will re-render the pkgdown site soon as well.
