### ISSUE TITLE
plot_corr(...., flagthresh =c( threshold1,threshold2, threshold3 )) not working

### ISSUE THREAD

**Issue by OscarSmallenbroek** [bluefoxr/COINr#24]
I tried to change the colors of a plot__corr with the flagthresh option. Changing the thresholds does not change the colors of the squares.
All positive correlations above the default threshold are green (OK) others are grey. Correlations above threshold 3 are also colored with green (OK).  The correlation structure I am using does not have negative correlations.  

code: 
plot_corr(coin, dset= "Aggregated",levels = 1 ,iCodes = list("IOI")
          ,flagcolours = TRUE, flagthresh = c(-0.3, 0.3, 0.7))

**Comment by bluefoxr** [comment]
Thanks for spotting this. Please download the dev version and the problem should be resolved.
