### ISSUE TITLE
Provide the option to use UnitName in COINr::iplotBar

### ISSUE THREAD

**Issue by Edouard-Legoupil** [bluefoxr/COINr#3]
For better legibility, it would be convenient to have the option to use UnitName in COINr::iplotBar

https://github.com/bluefoxr/COINr/blob/8510fdefcd0c87ec4659e49b0ae7a9255c3504f9/R/coin_resultsdash.R#l473

**Comment by bluefoxr** [comment]
Hi yes this is fairly easy to implement so I can add that feature in an update soon. Note that I will move the interactive plots to a separate add-on package in the next couple of months. See the README.

**Comment by bluefoxr** [comment]
Updated now - please download the dev version from GitHub and see the "xlabs" argument of iplotBar
