### ISSUE TITLE
Sensitivity Analysis parameters

### ISSUE THREAD

**Issue by Petrina95** [bluefoxr/COINr#31]
Hello again!

Is there a way to get the parameters used in every iteration in sensitivity analysis? I think the equivalent in COINr6 is the SAresults$Parameters which is missing from the result returned by COINr::get_sensitivity().

Thank you in advance,
Petrina

**Comment by bluefoxr** [comment]
Hi, yes you are right, I just added a fix for this, download the latest version from GitHub where you have a new `.$Para` output.

**Comment by Petrina95** [comment]
Thank you very much!
