### ISSUE TITLE
[refactor] add coord_flip() to plot_bar()

### ISSUE THREAD

**Issue by Edouard-Legoupil** [bluefoxr/COINr#38]
In plot_bar()

simply using  plot_bar() + coord_flip()   does not work as it then not sorted from high to low.

Better would be to add it directly as an option in the function

![image](https://user-images.githubusercontent.com/1789444/224165420-90545215-afeb-4e0a-979d-45737930de84.png)

**Comment by bluefoxr** [comment]
Sorting the bar chart (especially stacked) in ggplot2 is suprisingly fiddly, so I think this would take a bit of effort to sort out. At the end of the day, users can also build their own plots so I see this outside of the scope of COINr. Feel free to make a PR though if you know how to do it and I will merge it into the package if it works.

**Comment by bluefoxr** [comment]
Actually I changed my mind on this! See commit above.
