### ISSUE TITLE
Error in FUN(X[[i]], ...) :    One or more non-NA values of x has changed as a result of imputation. Check the behaviour of the imputation function.

### ISSUE THREAD

**Issue by Greggydp** [bluefoxr/COINr#40]
Hello,
I've been using the package for a few months now and didn't have any specific error that couldn't be fixed with a simple research: last week I decided to implement "groups" in my raw datasets. Using the "i_mean_grp" imputation function I encountered the error above, which confused me quite a bit, since imputation should never change non-NA values. Do you have any explanation simple explanation? Should I avoid using groups? 

Best,
Gregorio

**Comment by bluefoxr** [comment]
Hi please can you send me a reproducible example? I.e. the command you are running and the data you are running the command on, or a reproducible script. It may be a bug but it's hard to fix without being able to reproduce the error here.

**Comment by Greggydp** [comment]
Hi, sure! 
I'm trying to create a few composite indicators using data from Eurostat and OECD from 2000 to 2020, so I chose to use COINr for the recent update of the PURSE objects, which seem easy to manage and analyze. I tried the Impute() function both on the PURSE object and on a single COIN in the PURSE (the one for the year 2000 that you can see in the code line).

`purse <- Impute(purse, dset = "Raw", f_i = "i_mean_grp", use_group = "Land_group", impute_by = "column", out2 = "coin")`
`purse$coin$"2000" <- Impute(purse$coin$"2000", dset = "Raw", f_i = "i_mean_grp", use_group = "Land_group", impute_by = "column")`

I'm sorry, is one of my first times using GitHub and I'm entering the "world of coding" just now in the last few months, I hope I'm not too unorthodox. This is the dataset including the "environmental indicators", so the groups I'm trying to use refer to the Land Area of countries. Thanks for the fast reply.

[AmbIndData.csv](https://github.com/bluefoxr/COINr/files/11663222/AmbIndData.csv)

**Comment by Greggydp** [comment]
Yes of course, I'm sending you both my workspace and my "purse" object with attached data and metadata used for the creation, once again sorry for the little experience and knowledge I have with the platform and thank you.

[rdata_purseAmbiente.zip](https://github.com/bluefoxr/COINr/files/11664993/rdata_purseAmbiente.zip)

**Comment by Greggydp** [comment]
You were of great help, thank you so much for looking into my problem. I will install the github version, but I already ran a small check after converting the integers into numbers manually and the imputation function worked as intended. Thanks again.

Best regards,
Gregorio 

p.s. hope to get more and more into GitHub and the community 'cause It looks fire

**Comment by bluefoxr** [comment]
Great, thanks for spotting the bug as well, as this also helps improve the package.
