### ISSUE TITLE
Ability to override weights in a particular level of aggregation

### ISSUE THREAD

**Issue by pravanos** [bluefoxr/COINr#42]
Hello @bluefoxr!

I have spotted an issue and have found a potential remedy to it. It concerns overriding the existing pre-defined set of weights in .$Meta$Weights$Original but only in a particular level of aggregation. 

I encountered this issue when trying to use different argentation functions for different levels of aggregation, where one of the aggregation functions does not need weights. In this case, specifying "w="none"" in Aggregate( ) function would not suffice, as it would override all the weights. 
The partial remedy I found was to manually change the weights I wanted overridden into NA, and specify the custom function into receiving NA weights. Here is a reproducible piece of code:

#build coin up to Normalisation
ASEM <- build_example_coin(up_to = "Normalise")

#define function not receiving weights, e.g., y=max(x)
#The function should have w as an argument and specified as NA

a_max <- function(x, w=NA){
      y = max(x)
      return(y) }

#define new weight set equal to the original weights

w1 <- ASEM5$Meta$Weights$Original

#make the weights that should be overridden to NA, in this case only the weights corresponding to the aggregation from Level 3 to Level 4

w1$Weight[w1$iCode == "Conn"] <- NA
w1$Weight[w1$iCode == "Sust"] <- NA

#Aggregate using w=w1

ASEM <- Aggregate(ASEM, f_ag = c("a_amean","a_amean","a_max"), w=w1, dset = "Normalised")

I am not sure whether it would be possible to adjust the "w" argument in function Aggregate( ) so as to accept different values for the different aggregation levels. 

For instance, specifying w = list(NULL, NULL, "none") could be a solution that informs the function to search for weights in iMeta for the first 2 aggregation levels and not pass any weights for the last aggregation level. Not sure how it can be modelled though. 

All the best!

**Comment by bluefoxr** [comment]
This has been implemented, closing issue.

**Comment by liuyanguu** [comment]
Is it possible to apply weights by variable? For example, I have four indicators, and I want to weight each by a weight variable: 
index = ind1 * w1 + ind2 * w2 + ind3 * w3 + ind4 * w4

i.e., the weights for each indicator are different by country. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lyhel/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lyhel/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


indicator   1 | indicator 2 | indicator 3 | indicator 4 | w1 | w2 | w3 | w4
-- | -- | -- | -- | -- | -- | -- | --
0.99 | 0.99 | 0.16 | 0.60 | 0.20 | 0.60 | 0.10 | 0.10
1.00 | 1.00 | 0.60 | 0.14 | 0.10 | 0.50 | 0.20 | 0.30
1.00 | 1.00 | 0.14 | 0.16 | 0.20 | 0.60 | 0.10 | 0.10
1.00 | 1.00 | 0.01 | 0.10 | 0.10 | 0.50 | 0.20 | 0.30



</body>

</html>

**Comment by bluefoxr** [comment]
You'll need to write a custom aggregation function for that one, and pass to Aggregate() probably with `by_df = TRUE`.
https://bluefoxr.github.io/COINr/articles/aggregate.html#external-functions
