### ISSUE TITLE
Passing a data frame and a vector to Aggregate( ) in different aggregation levels

### ISSUE THREAD

**Issue by pravanos** [bluefoxr/COINr#43]
Hello @bluefoxr !

I came across the following issue: I would like to use two different aggregation functions in different levels of aggregation. Function A accepts a vector as input and function B a data frame as input. As I understand, currently argument "by_df" in function "Aggregate( ) " can only accept one logical value. Could it be possible to adjust "by_df" to accept a list or column of logical values, one for each aggregation level? i.e., as is the case with f_ag or f_ag_para at the moment. 

All the best!

**Comment by bluefoxr** [comment]
This has now been implemented, closing issue.
