### ISSUE TITLE
COIN creation impossible with iData and iMeta checked OK.

### ISSUE THREAD

**Issue by MoujibChahid** [bluefoxr/COINr#44]
COIN creation impossible even with iData and iMeta checked OK. 
The resulting error message is as follows: 
> coin <- new_coin(iData = iData, iMeta = iMeta)
iData checked and OK.
iMeta checked and OK.
Error in new_coin(iData = iData, iMeta = iMeta) : 
  Column names from iData not found in iMeta (excluding special columns).

According to this error message, there are columns in iData that are not present in iMeta, whereas this is not true. I've tried several times but I still can't create the COIN.
Can anyone help me?

**Comment by bluefoxr** [comment]
Problem resolved (user error) - there was a column in iData not specified in iMeta.
