### ISSUE TITLE
Error while treating outliers

### ISSUE THREAD

**Issue by MoujibChahid** [bluefoxr/COINr#45]
A repetitive error is displayed when processing outliers. This occurs with both the "Treat" and "qTreat" functions. 

The error message is as follows: 
Error in while ((!passing | force_win) & below_winmax) { : 
  missing value where TRUE/FALSE needed

I've tried to follow the documentation but the problem persists. 

Please remedy the situation.

**Comment by bluefoxr** [comment]
Hi, please provide a reproducible example (the coin as Rdata or RDA file, plus exact command you are running) and I'll take a look.

**Comment by MoujibChahid** [comment]
[CompleteIndex2015.xlsx](https://github.com/bluefoxr/COINr/files/11868121/CompleteIndex2015.xlsx)
[Index2015.zip](https://github.com/bluefoxr/COINr/files/11868127/Index2015.zip)

Enclosed are the requested documents describing the problem encountered. 
I have tried the following functions: 

> library(readxl)
> iData <- read_excel("/Users/moujib0/Desktop/Index2015/CompleteIndex2015.xlsx", sheet = "iData")
                                                                                                                    
> iMeta <- read_excel("/Users/moujib0/Desktop/Index2015/CompleteIndex2015.xlsx", sheet = "iMeta")
                                                                                                                    
> library(COINr)
> coin <- new_coin(iData, iMeta, level_names = c("Indicator", "Pillar", "Index"))
iData checked and OK.
iMeta checked and OK.
Written data set to .$Data$Raw
> global_specs = list(f1 = "winsorise",
+                     f1_para = list(na.rm = TRUE,
+                                    winmax = 5,
+                                    skew_thresh = 2,
+                                    kurt_thresh = 3.5,
+                                    force_win = FALSE),
+                     f2 = "log_CT",
+                     f2_para = list(na.rm = TRUE),
+                     f_pass = "check_SkewKurt",
+                     f_pass_para = list(na.rm = TRUE,
+                                        skew_thresh = 2,
+                                        kurt_thresh = 3.5))
> coin <- qTreat(coin, dset = "Raw", winmax = 5)
Error in while ((!passing | force_win) & below_winmax) { : 
  missing value where TRUE/FALSE needed
> coin <- Treat(coin, dset = "Raw")
> print(coin)
A Workbook object.
 
Worksheets:
 Sheet 1: "Meta.Ind"
 

 Sheet 2: "Meta.Lineage"
 

 Sheet 3: "Meta.Weights.Original"
 

 Sheet 4: "Meta.Unit"
 

 Sheet 5: "Data.Raw"
 

 
 Worksheet write order: 1, 2, 3, 4, 5
 Active Sheet 1: "Meta.Ind" 
	Position: 1

Warning messages:
1: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object
2: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object
> check_SkewKurt(coin, na.rm = FALSE, skew_thresh = 2, kurt_thresh = 3.5)
Error in skew(x, na.rm = na.rm) : is.numeric(x) is not TRUE
> global_specs = list(f1 = "winsorise",
+                     f1_para = list(na.rm = TRUE,
+                                    winmax = 5,
+                                    skew_thresh = 2,
+                                    kurt_thresh = 3.5,
+                                    force_win = FALSE),
+                     f2 = "log_CT",
+                     f2_para = list(na.rm = TRUE),
+                     f_pass = "check_SkewKurt",
+                     f_pass_para = list(na.rm = TRUE,
+                                        skew_thresh = 2,
+                                        kurt_thresh = 3.5))
> check_SkewKurt(coin, na.rm = FALSE, skew_thresh = 2, kurt_thresh = 3.5)
Error in skew(x, na.rm = na.rm) : is.numeric(x) is not TRUE

**Comment by bluefoxr** [comment]
The update that fixed that problem was made some months ago but not yet pushed to CRAN.

For a full example, just follow the commands in `build_example_coin()` (ignore the if statements etc).
https://github.com/bluefoxr/COINr/blob/a70bc83889d7fcafd000f8c4020110db4105bae5/R/examples.R#L42
