### ISSUE TITLE
Leave one out plot

### ISSUE THREAD

**Issue by coppertank** [bluefoxr/COINr#59]
First of all, I would like to compliment on the package and the clarity of the vignettes, highly appreciated.

I apologize in advance for the request if it doesn't comply with the idea of ​​the package, but I'll try anyway: I think it would be nice being able to specify in the `plot_scatter` function to plot all the indicators within a sub-pillar (or all the sub-pillars within a pillar) minus one.

This idea comes from reading the paper from Schlossarek et al. [The Importance of Variables in Composite Indices:
A Contribution to the Methodology and Application to Development Indices](https://link.springer.com/article/10.1007/s11205-019-02125-9?wt_mc=Internal.Event.1.SEM.ArticleAuthorOnlineFirst&ArticleAuthorOnlineFirst_20190521). 

According to this paper, an indicator whose drop would cause the highest loss of the information provided by the index is the most important. In the appendix, in fact, there are the comparison of the information loss captured by plotting the whole index (or pillar, or sub-pillar) on one axis and the same index minus one of its components at a time, for all the components.

I think it would be a great implementation to reduce the number of indicators

**Comment by bluefoxr** [comment]
Hi @coppertank I'm not sure if I fully understood you, but is this something similar to the [Removing elements](https://bluefoxr.github.io/COINr/articles/sensitivity.html#removing-elements) functionality?

**Comment by coppertank** [comment]
Exactly!
Just to be clear, the following image taken from the paper shows the Quality of Life component without one of its component at a time:
![Screenshot 2024-06-11 172128](https://github.com/bluefoxr/COINr/assets/119599103/17e702a7-790e-47d7-90de-a2173264b181)

Is there a way to achieve the same result graphically with the use of the function `plot_scatter`?

Thanks in advance

**Comment by bluefoxr** [comment]
No this can't be done directly with `plot_scatter()`, but what you could do is run the `remove_elements()` function and store the results as a list. Then have a look at the `.$Scores` table within that output list: this gives the scores resulting from the index with each element removed one at a time. It should only take a little wrangling to feed that into ggplot2 to get the plots above using e.g. faceting.

**Comment by coppertank** [comment]
I will try, thanks for the answer!

**Comment by coppertank** [comment]
As you suggested yesterday, I was able to store the results from removing one component at a time from the `.$Scores` table, store them in a dataset with the unaltered supbillar and plot the results. Thanks again for your availability!
