### ISSUE TITLE
Empty examples in online vignettes 

### ISSUE THREAD

**Issue by bauer-alex** [bluefoxr/COINr#9]
Issue based on the JOSS revision process (see [the corresponding issue](https://github.com/openjournals/joss-reviews/issues/4567)).

Currently, the two _Examples_ subpages on [bluefoxr.github.io/COINr](https://bluefoxr.github.io/COINr/) are empty. Please fill them or delete these subpages for the moment. Also without them you currently have enough examples in the other vignettes.

**Comment by bluefoxr** [comment]
Ok yes these are placeholders where I wanted to include examples where data is acquired through APIs and then processed through the package. However at the moment I don't have time to finish these so I will delete them as suggested. Will need to regenerate the pkgdown site so this will take a short while.

**Comment by bluefoxr** [comment]
I have now removed these so I will close the issue.
